# Data Tools
import numpy as np

# Pytorch
import torch
import torch.nn as nn
import torch.nn.init as init

# EMBER
import ember

# SKLearn
from sklearn.metrics import roc_auc_score, confusion_matrix, accuracy_score

# Misc
import os

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def get_clean_data(data_dir):
    """
    Retrieves previously vectorized EMBER dataset from the given directory and removes class -1 samples

    :param data_dir: str
                     EMBER dataset directory
    :return: float
            training features, training labels, testing features, testing labels
    """

    # EMBER data load
    X_train, y_train, X_test, y_test = ember.read_vectorized_features('{0}ember2018/'.format(data_dir))

    # Filter unlabeled data
    train_rows = (y_train != -1)
    X_train = X_train[train_rows]
    y_train = y_train[train_rows]
    test_row = (y_test != -1)
    X_test = X_test[test_row]
    y_test = y_test[test_row]

    return X_train, y_train, X_test, y_test


def get_adversarial_examples(data_dir, num_features, attack_name="GNN"):
    """
    Retrieves adversarial examples previously generated by the specified attack

    :param data_dir: directory "Adversarial_example_sets"
    :param num_features: number of features of EMBER dataset (2381 for EMBER 2018 version)
    :param attack_name: DEFCON 2019 malware evasion competition winner attacks used in the paper
    :return: adversarial example set of size (adversarial_example_size[attack_name] X 2381)
    """

    # EMBER adversarial example names and sizes (please refer to the paper for the names)
    adversarial_example_size = {"GNN": 1001, "GLGBM": 1001, "GAdv": 1000, "C1Pad": 2000,
                                "C2Pad": 2000, "StrPad": 2000}
    filename = os.path.join(data_dir, attack_name)
    # Load adversarial example features
    adversarial_example_feat = np.memmap(filename, dtype='float32', mode='r',
                                         shape=(adversarial_example_size[attack_name], num_features))

    return adversarial_example_feat


def omega(data_dir, num_features, perturbation_constraint="Uniform"):
    """
    Checks perturbation type. Generates the transformation matrix (represented by :math:`\Omega` in the paper) which is
    multiplied by delta in norm ball constraint of PGD algorithm.

    :param data_dir: directory "nonuniform_omega"
    :param num_features: number of features of EMBER dataset (2381 for EMBER 2018 version)
    :param perturbation_constraint: string that determines which transformation matrix wil be multiplied with delta in
    PGD norm ball constraint
    :return: transformation matrix tensor
    """

    if perturbation_constraint == "Uniform":
        # Uniform perturbation constraint
        omega_matrix = np.eye(num_features)

    elif perturbation_constraint == "Masked":
        # Masking features except "Byte Histogram", "Byte Entropy Histogram", "Section Information" (First 767 features)
        omega_matrix = np.eye(num_features)
        omega_matrix[767:, 767:] = 0

    elif perturbation_constraint == "Pearson":
        # Load Pearson coefficient, take the inverse of its absolute values and normalize
        pearson_cor = np.abs(np.load(data_dir + 'Pearson_correlations.npy')[:-1])
        pearson_cor[np.isnan(pearson_cor)] = 1e-8
        pearson_cor = 1 / pearson_cor
        omega_matrix = np.diag(pearson_cor / (np.linalg.norm(pearson_cor)))

    elif perturbation_constraint == "SHAP":
        # Load absolute values of shapley values, take its inverse and normalize
        shap_values = np.load(data_dir + 'Shapley_values.npy')
        shap_values[shap_values == 0] = 1e-8
        shap_values = 1 / shap_values
        omega_matrix = np.diag(shap_values/(np.linalg.norm(shap_values)))

    elif perturbation_constraint == "Mahalanobis":
        # Load decomposed inverse covariance of the training data
        omega_matrix = np.load(data_dir + 'MD_Transform.npy')  # All samples

    elif perturbation_constraint == "Mahalanobis benign":

        # Load decomposed inverse covariance of the benign samples from training data
        omega_matrix = np.load(data_dir + 'MD_Benign.npy')  # Only benign samples

    else:
        omega_matrix = []
        print("You entered an invalid constraint transformation! Please customize omega for your choice.")

    return torch.tensor(omega_matrix).float().to(device)


# L2-PGD Attack Implementation
def omega_norm(Z, Omega):
    """
    Calculates norm(Omega * Z)

    :param Z: delta perturbation
    :param Omega: transformation matrix
    :return: l2 norm of delta multiplied by Omega
    """
    return torch.matmul(Omega, Z.view(Z.shape[0], -1).T).T.norm(dim=1)


# l2 PGD
def pgd_l2(model, X, y, config):
    """
    Generates delta perturbations for the given clean class 1 samples using l2 PGD algorithm

    :param model: neural network
    :param X: malicious class samples to be perturbed
    :param y: malicious class labels
    :param config: configuration which contains parameters
                epsilon: norm ball constraint value
                num_restarts: number of random initializations for delta
                num_iter: number of steepest descent iterations
                alpha: normalized steepest descent update factor
                omega: transformation matrix to be multiplied by delta for norm ball constraint
    :return: delta perturbations for the given samples and model
    """
    epsilon = config['epsilon']

    # Initialize maximum loss and maximum delta
    max_loss = torch.zeros((y.shape[0])).to(device)
    max_delta = torch.zeros_like(X)

    for restart in range(config['num_restarts']):
        # Initialize delta randomly
        delta = torch.rand_like(X, requires_grad=True)
        delta.data = delta.data * 2 * epsilon - epsilon

        for iteration in range(config['num_iter']):

            # Defender loss
            loss = nn.CrossEntropyLoss()(model(X + delta), y.long())
            loss.backward()

            # Normalized steepest descent update
            delta.data += config['alpha'] * delta.grad.detach() / delta.grad.detach().norm(dim=1).view(-1, 1)

            # Projection of delta: Normalization by selected perturbation constraint
            delta.data *= epsilon / omega_norm(delta.detach(), config['omega']).view(-1, 1).clamp(min=epsilon)

            delta.grad.zero_()
        # Selection of the most adversarial perturbation in different restarts
        all_loss = nn.CrossEntropyLoss(reduction='none')(model(X + delta), y.long())
        max_delta[all_loss >= max_loss, :] = delta.detach()[all_loss >= max_loss, :]
        max_loss = torch.max(max_loss, all_loss)

    return max_delta


def get_trained_model(config, num_features):
    """
    Adversarially trains the model using delta perturbations which are generated by l2 PGD algorithm, and tests on clean
    test set and adversarial examples after each epoch.

    :param config: configuration which contains parameters
                TrainData: training set
                TestData: testing set
                batch_size: batch size for training
                learning_rate: learning rate of the optimizer
                num_epochs: number of training epochs
                AdversarialExamples: adversarial example set retrieved by "get_adversarial_examples"
                adversarial_example_rate: ratio between the number of perturbed class 1 samples and entire class 1
                                        samples (0.9 in the paper)
                threshold: probability threshold for decision

    :param num_features: number of features of EMBER dataset (2381 for EMBER 2018 version)
    :return: adversarially trained model, a list of model's roc_auc score on clean test set , number of evading
            adversarial examples, clean accuracy on test set
    """

    # Model Structure
    model = nn.Sequential(nn.Linear(num_features, 512), nn.ReLU(), nn.Dropout(0.2),
                          nn.Linear(512, 256),          nn.ReLU(), nn.Dropout(0.2),
                          nn.Linear(256, 128),          nn.ReLU(), nn.Dropout(0.2),
                          nn.Linear(128, 2)).to(device)

    # Weight initialization
    def init_weights(m):
        if type(m) == nn.Linear:
            init.kaiming_uniform_(m.weight, nonlinearity='relu')

    # Initialize the model
    model.apply(init_weights)
    # Specify loss function
    criterion = nn.CrossEntropyLoss()
    # Specify optimizer
    optimizer = torch.optim.Adam(model.parameters(), lr=config['learning_rate'])

    # Create data loaders
    train_loader = torch.utils.data.DataLoader(config['TrainData'], batch_size=config['batch_size'],
                                               shuffle=True, num_workers=20)
    test_loader = torch.utils.data.DataLoader(config['TestData'], batch_size=config['TestData'].__len__(),
                                              shuffle=False, num_workers=20)
    # Create adversarial example (AE) tensor
    ae = torch.tensor(config['AdversarialExamples']).to(device)

    running_loss = 0
    performance_metrics = [[] for _ in range(3)]
    # Training the model
    model.train()

    for epoch in range(config['num_epochs']):

        for inputs, target in train_loader:

            inputs, target = inputs.to(device), target.long().to(device)

            # Get malicious sample indexes from the batch
            malicious = (target.data.cpu() == 1)
            # Randomly select the indexes of malicious samples for the given percentage: %90
            ae_rate = int(config['adversarial_example_rate'] * malicious.sum())
            ae_index = np.where(malicious)[0][np.random.randint(0, int(malicious.sum()), ae_rate)]
            # Call l2 PGD algorithm to get delta perturbations
            delta = pgd_l2(model, inputs[ae_index, :], target[ae_index], config)
            # Apply delta only to randomly selected malicious samples
            inputs.data[ae_index, :] += delta.data

            # Forward pass: compute predicted outputs by passing inputs to the model
            outputs = model(inputs)
            # calculate the loss
            loss = criterion(outputs, target)
            # Clear the gradients
            optimizer.zero_grad()
            # Backward pass: compute gradient of the loss with respect to model parameters
            loss.backward()
            # Perform a single optimization step (parameter update)
            optimizer.step()
            # Update running training loss
            running_loss += loss.item()

        # Test model after each epoch
        model.eval()

        with torch.no_grad():

            for input_test, labels in test_loader:
                input_test, labels = input_test.to(device), labels.long().to(device)

                output_test = model(input_test)
                test_loss = criterion(output_test, labels).item()
                # Find probability of predictions
                y_pred = torch.softmax(output_test, 1).data[:, 1].cpu()
                y_real = labels.cpu()

                # Performance metrics
                roc_auc = roc_auc_score(y_real, y_pred)
                tn, fp, fn, tp = confusion_matrix(y_real, y_pred > config['threshold']).ravel()
                accuracy = accuracy_score(y_real, y_pred > config['threshold'])

                # Testing evasion by adversarial examples for the specified attack
                evasion = (torch.softmax(model(ae), 1).data[:, 1] < config['threshold']).sum().cpu().numpy()

        print(f'Epoch: {epoch + 1}.. '
              f'Train loss: {running_loss / len(train_loader):.4f}.. '
              f'Test loss: {test_loss / len(test_loader):.4f}.. '
              f'FPR: {(100 * fp) / labels.shape[0]:.3f}.. '
              f'FNR: {(100 * fn) / labels.shape[0]:.3f}.. '
              f'Test acc: {accuracy:.3f}.. '
              f'ROCAUC: {roc_auc:.5f} .. '
              f'Number of evasions: {evasion} .. ')
        performance_metrics[0].append(roc_auc)
        performance_metrics[1].append(evasion)
        performance_metrics[2].append(accuracy)
        running_loss = 0
        model.train()

    return model, performance_metrics
